// ─── BLOG DATA ───────────────────────────────────────────────────────────────
// publishedAt: { platform: "url" } | null (null = native reader)
// platform options: "substack" | "lesswrong" | "x" | null
// draft: true = visible but dimmed, unclickable
// featured: true = appears in highlights panel

export const blogData = {
  nodes: [
    // ── ABOUT NODE (special — always present, fixed position) ────────────────
    {
      id: "about",
      type: "about",
      title: "Swasti",
      excerpt: "Researcher & builder at the intersection of AI systems and the humans who build and use them.",
      tags: [],
      fixed: true,
    },

    // ── MAIN ARTICLES ────────────────────────────────────────────────────────
    {
      id: "distillation-attacks",
      type: "implementation",
      title: "Distillation Attacks on LLMs",
      excerpt: "How model distillation can be exploited to transfer adversarial vulnerabilities across model families — and why this matters for AI safety.",
      tags: ["AI Safety", "ML Security"],
      date: "2026-02",
      readTime: 5,
      publishedAt: null,
      featured: true,
      draft: false,
    },
    {
      id: "model-collapse",
      type: "exploratory",
      title: "Model Collapse & Synthetic Data",
      excerpt: "What happens when models train on their own outputs recursively — a deep dive into the collapse phenomenon and mitigation strategies.",
      tags: ["AI Safety", "Training", "Information Provenance"],
      date: "2025-11",
      readTime: 8,
      publishedAt: null,
      featured: true,
      draft: false,
    },
    {
      id: "rag-security",
      type: "project",
      title: "RAG Security Scanner",
      excerpt: "Building a retrieval-augmented generation pipeline with security primitives — prompt injection detection, embedding poisoning resistance, and audit trails.",
      tags: ["Security", "RAG", "AI Safety"],
      date: "2026-07",
      readTime: 15,
      publishedAt: null,
      featured: false,
      draft: false,
    },
    {
      id: "eval-reliability",
      type: "opinion",
      title: "Evaluation Reliability in ML",
      excerpt: "A reproducibility failure found in ChromaDB prompted this investigation into how evaluation frameworks silently diverge across environments.",
      tags: ["Evals", "Research"],
      date: "2026-07",
      readTime: 8,
      publishedAt: null,
      featured: false,
      draft: false,
    },
    {
      id: "hci-safety",
      type: "exploratory",
      title: "HCI at the AI Safety Boundary",
      excerpt: "Notes from thinking about the human layer — how interface design choices upstream of the model affect alignment downstream.",
      tags: ["HCI", "AI Safety"],
      date: "2026-07",
      readTime: 7,
      publishedAt: null,
      featured: false,
      draft: true,
    },
    {
  id: "emb-eval",
  type: "exploratory",
  title: "Choosing an Embedding Model for Telephony Retrieval",
  excerpt: "Findings from a comparative evaluation of three models on a multilingual, latency-sensitive production system — and what MRL actually means in practice.",
  tags: ["RAG", "Evals", "Research"],
  date: "2026-06",
  readTime: 10,
  publishedAt:  {html: "/articles/emb-eval.html" },
  featured: false,
  draft: false,
},
 
{
  id: "chromadb-score-discrepancy",
  type: "opinion",
  title: "Chasing a Score Discrepancy Through Eight Layers of ChromaDB",
  excerpt: "Identical code, identical corpus, identical embeddings — two production environments that still disagreed on every confidence score. An eight-layer elimination that ended without a clean answer.",
  tags: ["Evals", "RAG", "Research"],
  date: "2026-07",
  readTime: 10,
  publishedAt: { html: "/articles/chromadb-score-discrepancy.html" },
  featured: true,
  draft: false,
},
{
  id: "intel-sgx",
  type: "exploratory",
  title: "Intel SGX: The CPU-Based Defense System",
  excerpt: "SGX seemed impenetrable — private enclaves, CPU-level encryption, even Spectre-resistant. Then came SGXPECTRE and ÆPIC Leak. A look at how the attack surface evolved and what remained useful.",
  tags: ["Security", "HCI"],
  date: "2022-11",
  readTime: 5,
  publishedAt: null,
  featured: false,
  draft: false,
},
 
{
  id: "xenobots",
  type: "exploratory",
  title: "Xenobots: The First Ever Living Robots",
  excerpt: "Living, programmable organisms designed on a supercomputer and assembled by biologists. Less than a millimeter wide, capable of movement, self-healing, and kinetic replication. Notes on something genuinely strange.",
  tags: ["Research"],
  date: "2023-02",
  readTime: 4,
  publishedAt: null,
  featured: false,
  draft: false,
},
 
{
  id: "captcha",
  type: "exploratory",
  title: "CAPTCHA: What Is It and How Does It Work?",
  excerpt: "From distorted text that bots could eventually read, to cursor path analysis and full browsing history assessment. How the arms race between CAPTCHAs and ML evolved — and where it stands now.",
  tags: ["Security", "Research"],
  date: "2023-03",
  readTime: 5,
  publishedAt: null,
  featured: false,
  draft: false,
},
 
{
  id: "lava-lamps",
  type: "exploratory",
  title: "How Lava Lamps Help With Internet Encryption",
  excerpt: "Computers run on logic, which makes them bad at randomness — and randomness is load-bearing for encryption. How Cloudflare solved this with 100 lava lamps and a camera.",
  tags: ["Security", "Research"],
  date: "2023-04",
  readTime: 6,
  publishedAt: null,
  featured: false,
  draft: false,
},
 
{
  id: "clock-sync",
  type: "exploratory",
  title: "Automatic Synchronisation of Clocks and Devices",
  excerpt: "Watching clocks flip at midnight during Daylight Savings Time led to a genuine question: how does every device just know? NTP, GPS atomic clocks, stratum hierarchies, and why this matters beyond phones.",
  tags: ["Research"],
  date: "2023-04",
  readTime: 6,
  publishedAt: null,
  featured: false,
  draft: false,
},
    // ── REFERENCE NODES ──────────────────────────────────────────────────────
    {
      id: "knowledge-distillation",
      type: "ref",
      title: "Knowledge Distillation (Hinton et al., 2015)",
      excerpt: "Original paper introducing soft target distillation for model compression.",
      tags: ["Paper"],
      parent: "distillation-attacks",
      url: "https://arxiv.org/abs/1503.02531",
    },
    {
      id: "adversarial-transfer",
      type: "ref",
      title: "Adversarial Transferability",
      excerpt: "Szegedy et al. on adversarial examples transferring across architectures.",
      tags: ["Paper"],
      parent: "distillation-attacks",
      url: "https://arxiv.org/abs/1312.6199",
    },
    {
      id: "model-stealing",
      type: "ref",
      title: "Model Stealing via API Queries",
      excerpt: "Black-box extraction attacks on commercial ML APIs.",
      tags: ["Paper"],
      parent: "distillation-attacks",
      url: "https://arxiv.org/abs/1610.05820",
    },
    {
      id: "shumailov-collapse",
      type: "ref",
      title: "The Curse of Recursion — Shumailov et al.",
      excerpt: "Foundational paper on model collapse in self-consuming training loops.",
      tags: ["Paper"],
      parent: "model-collapse",
      url: "https://arxiv.org/abs/2305.17493",
    },
    {
      id: "synthetic-data-survey",
      type: "ref",
      title: "Survey: Synthetic Data for LLM Training",
      excerpt: "Comprehensive overview of synthetic data generation techniques and pitfalls.",
      tags: ["Survey"],
      parent: "model-collapse",
      url: "https://arxiv.org/abs/2402.13799",
    },
    {
      id: "prompt-injection",
      type: "ref",
      title: "Prompt Injection Attacks",
      excerpt: "Taxonomy of injection vectors in RAG and tool-augmented LLMs.",
      tags: ["Paper"],
      parent: "rag-security",
      url: "https://arxiv.org/abs/2302.12173",
    },
    {
      id: "embedding-poisoning",
      type: "ref",
      title: "Embedding Space Poisoning",
      excerpt: "Adversarial manipulation of dense retrieval indexes.",
      tags: ["Paper"],
      parent: "rag-security",
      url: "https://arxiv.org/abs/2310.19156",
    },
    {
      id: "chromadb-issue",
      type: "ref",
      title: "ChromaDB Reproducibility Failure",
      excerpt: "Independently discovered: distance metric inconsistency across versions.",
      tags: ["Finding"],
      parent: "eval-reliability",

    },
    {
      id: "embedding-evals",
      type: "ref",
      title: "Embedding Model Evaluation Study",
      excerpt: "Comparative evaluation of embedding models across semantic similarity benchmarks.",
      tags: ["Research"],
      parent: "eval-reliability",
    },
    {
  id: "mrl-model-card",
  type: "ref",
  title: "static-similarity-mrl-multilingual-v1 (HuggingFace)",
  excerpt: "Model card for the MRL multilingual embedding model used in the evaluation.",
  tags: ["Model"],
  parent: "emb-eval",
  url: "https://huggingface.co/sentence-transformers/static-similarity-mrl-multilingual-v1",
},
{
  id: "mpnet-ref",
  type: "ref",
  title: "all-mpnet-base-v2 (Sentence Transformers)",
  excerpt: "Sentence Transformers' highest-quality general-purpose embedding model.",
  tags: ["Model"],
  parent: "emb-eval",
  url: "https://huggingface.co/sentence-transformers/all-mpnet-base-v2",
},
{
  id: "hnsw-ref",
  type: "ref",
  title: "Efficient and Robust Approximate Nearest Neighbor Search (HNSW)",
  excerpt: "Malkov & Yashunin, 2018 — the paper behind the approximate index at the root of the discrepancy.",
  tags: ["Paper"],
  parent: "chromadb-score-discrepancy",
  url: "https://arxiv.org/abs/1603.09320",
},
{
  id: "chroma-v1-ref",
  type: "ref",
  title: "ChromaDB v1.0 Release — Rust Rewrite Announcement",
  excerpt: "Official announcement of the Rust-core rewrite that changed the API path from SegmentAPI to RustBindingsAPI.",
  tags: ["Docs"],
  parent: "chromadb-score-discrepancy",
  url: "https://trychroma.com/blog/2025-04-24-chroma-1.0",
},
  ],

  edges: [
    { source: "distillation-attacks", target: "knowledge-distillation" },
    { source: "distillation-attacks", target: "adversarial-transfer" },
    { source: "distillation-attacks", target: "model-stealing" },
    { source: "model-collapse",       target: "shumailov-collapse" },
    { source: "model-collapse",       target: "synthetic-data-survey" },
    { source: "rag-security",         target: "prompt-injection" },
    { source: "rag-security",         target: "embedding-poisoning" },
    { source: "eval-reliability",     target: "chromadb-issue" },
    { source: "eval-reliability",     target: "embedding-evals" },
    // cross-article connections
    { source: "distillation-attacks", target: "model-collapse" },
    { source: "model-collapse",       target: "eval-reliability" },
    { source: "rag-security",         target: "eval-reliability" },
    { source: "hci-safety",           target: "distillation-attacks" },
    { source: "emb-eval", target: "chromadb-score-discrepancy" },
  // chromadb finding connects to the broader eval-reliability article
  { source: "chromadb-score-discrepancy", target: "eval-reliability" },
  { source: "intel-sgx",  target: "rag-security" },
 
// CAPTCHA → eval reliability (ML robustness angle)
{ source: "captcha",    target: "eval-reliability" },
 
// Lava lamps → encryption / security cluster
{ source: "lava-lamps", target: "intel-sgx" },
  ],
}
