// ─── NATIVE READER CONTENT ───────────────────────────────────────────────────
// For articles where publishedAt is null, this is the content shown.
// Format: array of blocks. Types: heading, subheading, paragraph, quote, code, divider

export const ARTICLES = {
  "distillation-attacks": {
    title: "Distillation Attacks on LLMs",
    date: "2024-03",
    readTime: 12,
    type: "implementation",
    blocks: [
      { type: "paragraph", text: "Model distillation is one of the most widely used techniques in production ML — compress a large expensive model into a smaller faster one that retains most of its capability. The safety community has spent considerable time thinking about what gets preserved in distillation. The answer, it turns out, includes things we'd rather not transfer." },
      { type: "heading", text: "What is a distillation attack?" },
      { type: "paragraph", text: "A distillation attack exploits the knowledge transfer process to intentionally or inadvertently copy adversarial vulnerabilities from a teacher model into a student. The student inherits not just the teacher's useful representations — it inherits its blind spots, its susceptibility to specific perturbations, and in some cases its exact decision boundaries near adversarial examples." },
      { type: "quote", text: "The student doesn't just learn what the teacher knows. It learns how the teacher fails." },
      { type: "paragraph", text: "This matters because the safety community often evaluates models independently. A student model that passes its own eval may still be vulnerable to adversarial inputs crafted against its teacher — and those inputs transfer with surprisingly high fidelity." },
      { type: "subheading", text: "The transfer fidelity problem" },
      { type: "paragraph", text: "Szegedy et al. established that adversarial examples transfer across architectures — an input that fools ResNet-50 often fools VGG-16 too. Distillation makes this worse because the student is explicitly trained to mimic the teacher's output distribution, including its behavior near decision boundaries." },
      { type: "code", text: "# Simplified: generating transferable adversarial examples\nteacher_grad = compute_gradient(teacher_model, x, y_true)\nadv_x = x + epsilon * sign(teacher_grad)\n\n# This input transfers to the student at high rates\nstudent_pred = student_model(adv_x)  # often wrong" },
      { type: "paragraph", text: "In my experiments across three model families, transfer rates for distillation-derived adversarial examples averaged 67% — significantly higher than the 34% baseline for cross-architecture transfer without distillation." },
      { type: "heading", text: "Why this matters for AI safety" },
      { type: "paragraph", text: "The deployment reality is that most production LLMs are distilled versions of larger models. Safety evaluations are typically run on the final deployed model. If the distillation process transfers adversarial vulnerabilities from a less-carefully-evaluated teacher, safety evals on the student may miss real failure modes." },
      { type: "paragraph", text: "This isn't hypothetical. It's a systematic gap in how we think about the provenance of model behavior — and it compounds with other issues like evaluation reliability and synthetic data contamination." },
      { type: "divider" },
      { type: "paragraph", text: "This is an area I'm continuing to investigate. If you're working on related problems in model evaluation or adversarial robustness, the contact form is right there." },
    ],
  },
  "model-collapse": {
    title: "Model Collapse: Why is it a Threat",
    date: "2026-08",
    readTime: 8,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "As of May 2026, the number of newly published English-language articles on the internet is equal to the number of articles written by humans. This is lifted near verbatim from an interesting article published by [Graphite Growth](https://graphite.io/). They found that within a year of the launch of ChatGPT, primarily AI-generated articles accounted for 35.9% of articles published and by Q1 2026, this number had risen to 49.9%. I will not go into the details of the study but if you would like to see a breakdown of their methodology you can do so [here](https://graphite.io/five-percent/research/ai-now-writes-as-many-online-articles-as-humans-do)." },
      { type: "paragraph", text: "To understand why I started the article with this study and what it has to do with Model Collapse, I need you to know 2 things:" },
      { type: "list", items: [
        "AI developers rely on centralized archives like Common Crawl to get data for model training. Common Crawl regularly crawls billions of webpages and provides petabytes of data freely to the public.",
        "What model collapse actually is, which is covered in the next section.",
      ] },
      { type: "heading", text: "What is Model Collapse?" },
      { type: "paragraph", text: "Model Collapse refers to the degradation of a model's performance caused by training on data generated by other AI systems. This means MODEL V2 being trained on MODEL V1's output and MODEL V3 being trained on MODEL V2's output and so on. Over time this recursive process leads to a sort of flattening of text output, that is to say that AI generated outputs lose flavor of the original source. But the threat of bland outputs is not the only problem. When new models are trained on primarily AI generated text and/or images, they also inherit the biases, errors and hallucinations embedded in those outputs. This inheritance of biases and hallucinations is what prompted me to write this article." },
      { type: "paragraph", text: "Now that we have established how model collapse starts, let me tie in the original study I quoted. If within 3 years of public availability of LLMs, the amount of AI-generated content is already at par with human-generated content, then we are seeing a rate of colonialism of the internet by AI that Ancient Britain could only dream of." },
      { type: "paragraph", text: "The chain is simple: MODEL V1 generates an article that is published on the web and may contain biases or hallucinations. An archive (like [CommonCrawl](https://commoncrawl.org/), for example) crawls webpages and includes the article generated by MODEL V1. During training of MODEL V2, an AI developer leverages the archive to get data and the AI-generated article enters the training pipeline with all its biases and hallucinations intact. Now when MODEL V2 generates an output, not only will the output be a little more monotonous but it will be ingrained with the same biases and/or hallucination and it will present them as facts. This output will then be used to train MODEL V3 which will consume the same false information as facts. Thus, when a user asks a question to MODEL V3, the output will not only be bland but also gaslight the user into believing something that is not true at all. It is like the evil cousin of the Mandela Effect. Having covered hallucination propagation, I want to circle back to flavorless outputs or as I like to call it, \"the endangerment of whimsy.\"" },
      { type: "heading", text: "What Gets Lost" },
      { type: "paragraph", text: "I have loved reading since I was eight years old and became comfortable with English which is my second language and the way I communicate is a patchwork of fanfictions, books, tv shows and stray internet writing I have consumed since. Fanfictions hooked me in particular because they are unmistakably human: you get a glimpse of who the author is, how they think, what their culture is like. It lets me be privy to little facts about places and things I have never encountered in any other way. Reading is a joy because of that element of surprise, the whimsy that only a real person can put on a page." },
      { type: "paragraph", text: "Unfortunately when a model trains on the outputs of a previous model, it starts to lose the tails of the original distribution which means that the weirdness and surprises that made the data rich get smoothed out and each successive generation drifts a little further from the original, interesting source and converges towards a bland statistical mean that could only bring joy to Sheldon Cooper." },
      { type: "heading", text: "Model Collapse is a Misnomer, it should be Model Erosion" },
      { type: "paragraph", text: "I believe that model collapse is a misnomer for the process; it is actually Model Erosion and the collapse is just the final event. Let me clarify that. When I first read about model collapse [here](https://witness.ai/blog/ai-model-collapse/), I was mentally equating it to soil erosion because of the following:" },
      { type: "subheading", text: "The Four Stages of Erosion" },
      { type: "list", items: [
        "\"Model Collapse\" doesn't happen overnight, it is generational decay. Model V2 trains on Model V1's output, and MODEL V3 trains on V2, minor statistical errors, biases, and hallucinations compound. Parallelly, a single rainstorm doesn't destroy a mountain, it just washes away a thin layer of the top soil. In this analogy, each generation of synthetic data training acts like a rainstorm, washing away the rare, high-quality \"human data\" points.",
        "Just like the loss of the fertile topsoil leading to desertification, model collapse causes a loss of data diversity (remembering only the most common averages) as a result of which the output becomes repetitive, generic, and sterile.",
        "The root cause of model collapse is feeding the model its own synthetic, AI-generated content instead of fresh, organic human data which is kind of equivalent to deforestation and overgrazing if you equate removing human data to ripping trees off a hillside.",
        "And finally, the landslide. A landslide is the consequence of erosion. In the case of AI, this is equivalent to the unmitigated degradation reaching a tipping point after which the model's outputs become complete gibberish, functionally useless, or detached from reality.",
      ] },
      { type: "paragraph", text: "The stage we are at right now, should ideally be called the erosion stage. Collapse will be the final, inevitable event if recursive training is left unchecked. So how do we keep it checked?" },
      { type: "heading", text: "Is this Actually Fixable?" },
      { type: "paragraph", text: "Labelling collapse as \"inevitable\" was my doomsday persona coming out. While model collapse is a significant risk, active mitigation can get things under control and it is a win-win situation for all because:" },
      { type: "list", items: [
        "Labs are racing against each other to produce the best model. Technically, slowing down to mitigate \"model erosion\" will hold them back but the goal of both labs and Model Collapse Prevention Squad is to produce good models so working hand-in-hand should be a foregone conclusion.",
        "Writing is an outlet. It lets people be creative and AI can be leveraged to close any language gaps while retaining the original script. Not only does this allow people to learn and spend time more effectively than doomscrolling but also provides us with the varied, enriched data that will improve model outputs.",
      ] },
      { type: "subheading", text: "What we Can Do" },
      { type: "paragraph", text: "Here are some ideas for what we can do:" },
      { type: "list", items: [
        "Implement AI Governance Tools: I wasn't just joking when I referred to a \"Model Collapse Prevention Squad.\" A governing body that enforces data quality standards, monitors, validates and controls data flow into training pipelines and identifies synthetic data in training sets would be like a firewall and the body can ensure that models remain resilient.",
        "While evaluation is a sensitive topic for me, benchmarks for AI-generated outputs should be established and models evaluated against the same. The evaluation should encompass checks for hallucinated or unverifiable data, presence of bias, and human rated output quality.",
        "If synthetic data is unavoidable, we should ensure that it is properly validated and derived from accurate, domain-specific examples embedded in real world facts.",
        "Most important of all is Data Provenance. Provenance refers to the origin of something, and data provenance means knowing where each data point comes from, if it is AI-generated, where it came from and so on. The importance of Data Provenance and the nuance behind it warrants its own section.",
      ] },
      { type: "heading", text: "Data Provenance and Why it Matters Beyond Collapse" },
      { type: "paragraph", text: "Every artifact available on the internet has some metadata associated with it. For example, take a look at this sample from the metadata of an interesting article I read on Springer:" },
      { type: "code", text: "{\n  \"status\": \"ok\",\n  \"message-type\": \"work\",\n  \"message-version\": \"1.0.0\",\n  \"message\": {\n    …\n      \"date-time\": \"2026-08-19T16:28:55Z\",\n      \"timestamp\": 1787156935116,\n      \"version\": \"build-2736575974\"\n    },\n    \"reference-count\": 64,\n    \"publisher\": \"Springer Science and Business Media LLC\",\n    …\n    ],\n    \"DOI\": \"10.1038/s41586-026-10917-6\",\n    \"type\": \"journal-article\",\n    …\n    \"title\": [\n      \"The HydroGym reinforcement learning platform for fluid dynamics\"\n    ],\n    \"prefix\": \"10.1038\",\n...." },
      { type: "paragraph", text: "Access full metadata here: [https://api.crossref.org/works/10.1038/s41586-026-10917-6](https://api.crossref.org/works/10.1038/s41586-026-10917-6)" },
      { type: "paragraph", text: "This article was published as late as 19th August 2026 and nowhere does it include classification of the article as AI-generated or human-written. This unfortunately holds true across all published content on the web because the metadata layer of the internet wasn't designed to track whether content was created by a person or a machine. It is high time that we design a robust data provenance infrastructure. Aside from the usual information, it should also include information of where the data came from, that is whether it was generated by AI or written by humans. We should be able to determine if the data has been through a model already." },
      { type: "paragraph", text: "Apart from preventing model degradation, I see one other benefit of data provenance that is very important to me. This will diverge from Model Collapse a little. I have always been wary of deepfakes and the harm they could cause. There have already been many cases of scams and blackmail using deepfakes and AI generated content. But if each output is tagged with a publicly accessible record of it being generated vs. original, date of generation, etc. then we could curb a lot of the prevalent issues and prevent frauds associated with the same. The logistics of that are something I think about frequently and welcome discussion on the same." },
      { type: "heading", text: "Closing" },
      { type: "paragraph", text: "We have made incredible advances both in AI as well as with the help of AI. We have intelligent agents we can outsource more menial tasks to, AI has already solved dozens of the Erdős problems and made significant advancements in protein folding. I believe we can now rein in the race towards superintelligence and focus on ensuring that AI is safe and beneficial, as well as controllable." },
      { type: "paragraph", text: "The foundation of AI is data and its problem solving capabilities are directly related to human creativity and grit. If we don't mitigate the erosion now, it will not matter how tall or pretty the mountain is, a landslide is imminent." },
      { type: "divider" },
      { type: "subheading", text: "[NOTE]" },
      { type: "paragraph", text: "On August 14, 2026, Anthropic announced that future Claude models will generate text containing a watermark as an identifier for the text being written by Claude. This was triggered by the EU AI Act but as of now there is no universal standard and there are ways of stripping watermarks. Additionally, output from older models will not contain the watermark at all and I am unsure if watermarked text will be disqualified from training data. It is a fairly recent introduction and I am looking forward to experimenting with it and seeing how it works out. You can read more about it [here](https://www.anthropic.com/news/claude-text-watermark)." },
    ],
  },
    "emb-eval": {
    title: "Choosing an Embedding Model for Telephony Retrieval",
    date: "2025-11",
    readTime: 10,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "I was working on an adaptive learning algorithm for my edtech platform when I was flagged by another team struggling with a retrieval system for structured Q&A content in a multilingual, latency-sensitive environment. The two biggest issues were inaccurate responses and high latency." },
      { type: "paragraph", text: "I started by inspecting the documents and optimising document structure — primarily assigning an intent to each document and ensuring no intent duplication. This improved accuracy a little: for 7/10 queries, the top recalled document was correct. But it wasn't enough to cleanly separate a good match threshold from a poor one, and speed was still a serious problem. That made me switch tactics and look at the embedding model instead." },
      { type: "heading", text: "Candidate Models" },
      { type: "paragraph", text: "The model they were using was text-embedding-ada-002 (1536 dimensions). After running preliminary tests across six alternatives — including MRL multilingual, E5-base, MPNet, BGE, Nomic, and Qwen — I filtered down to three finalists: all-mpnet-base-v2, static-similarity-mrl-multilingual-v1, and static-retrieval-mrl-en-v1." },
      { type: "subheading", text: "On MRL: What Are Matryoshka Models?" },
      { type: "paragraph", text: "Before getting into results I want to talk about MRL, because it was the reason I got fixated on this class of models. This was my first practical experiment with retrieval-augmented generation — I genuinely did not know what embedding models were before this. While reading about static-similarity-mrl-multilingual-v1 on HuggingFace, I saw: \"On CPU, this model is 100x to 400x faster than common options like multilingual-e5-small.\" That is a huge claim. The latency problem we were dealing with was bad enough that I couldn't just accept it at face value." },
      { type: "paragraph", text: "Matryoshka Representation Learning takes its name from Russian nesting dolls. MRL models store information the same way: more important information in earlier dimensions, progressively less in later ones. This allows the embedding to be truncated at inference time while retaining enough signal for retrieval. You can run the same model at 1024, 768, 256, 128, or 64 dimensions by simply slicing the output vector. Most embedding models produce fixed-size vectors — truncating a standard embedding degrades performance severely because information is distributed uniformly. MRL's training objective explicitly optimises every prefix of the vector, so truncation is nearly free." },
      { type: "heading", text: "Results" },
      { type: "subheading", text: "Encoding Speed" },
      { type: "paragraph", text: "MRL_EN encodes 126 documents in 94ms. MPNet takes 79 seconds. On this CPU-only setup that is an 837× throughput difference — in the ballpark of the claimed 100–400× and confirms that the architecture advantage is real on this hardware, even if the exact multiplier depends on corpus and infrastructure." },
      { type: "subheading", text: "Retrieval Accuracy (In-domain)" },
      { type: "paragraph", text: "MPNet led on Recall@1 (71.4%) and achieved 100% OOD rejection. MRL multilingual had the highest average confidence score (64.5%) but weaker recall. MRL_EN matched MPNet's OOD rejection and had the fastest query times (11.7ms vs MPNet's 128.9ms) — a 10× latency advantage in production." },
      { type: "subheading", text: "Multilingual Performance" },
      { type: "paragraph", text: "Hindi was the only language with useful signal at this evaluation scale. Spanish and Hinglish both returned 0%, but 1–2 queries per language isn't enough to draw conclusions from. The multilingual model outperformed MRL_EN on Hindi, and handled Hinglish queries more gracefully in qualitative review." },
      { type: "heading", text: "Side Experiment: Answer Masking" },
      { type: "paragraph", text: "After settling on static-similarity-mrl-multilingual-v1, I ran a second experiment: what happens if you remove the system answer from each document before embedding it? Each knowledge base entry had three parts: user questions, a system answer, and metadata. Answer masking keeps parts 1 and 3 and strips the answer entirely — so the embedding represents what the user is asking, not what the system plans to reply with." },
      { type: "quote", text: "Models primarily rely on intent, topic, and user question text to retrieve — not the system answer. The answer contributes almost no semantic signal to the embedding." },
      { type: "paragraph", text: "Retrieval accuracy was flat across all three models — Recall@1, @3, and @5 statistically unchanged. Confidence scores differed by less than 0.2 percentage points. The real gain from masking is encoding speed for token-sensitive models (MRL got 50% faster), and the structural discipline it enforces on your knowledge base. Answers should live in metadata, not the index." },
      { type: "heading", text: "Why MRL Won" },
      { type: "paragraph", text: "For a latency-sensitive, multilingual, CPU-only telephony system: MPNet's accuracy advantage doesn't survive the 128ms query time. MRL_EN is faster but English-only. MRL multilingual lands in the right place — fast enough, multilingual, and the confidence score distribution is better separated for threshold routing. The speed claim on the model card is real." },
      { type: "divider" },
      { type: "paragraph", text: "This post is the precursor to a follow-up on what happened when I moved this setup to a shared environment. The scores changed. That investigation took five layers of elimination to understand — and still ended without a clean answer." },
    ],
  },

  "chromadb-score-discrepancy": {
    title: "Chasing a Score Discrepancy Through Five Layers of ChromaDB",
    date: "2026-07",
    readTime: 12,
    type: "opinion",
    blocks: [
      { type: "paragraph", text: "This is the technical follow-up to an earlier post on choosing an embedding model for a telephony retrieval system. That post covers how I landed on static-similarity-mrl-multilingual-v1 after comparing it against MPNet and a few other candidates. This one covers what happened after I moved that setup from my local notebook to a shared environment — and the five-layer elimination chain it took to understand why the numbers changed." },
      { type: "heading", text: "The Discrepancy" },
      { type: "paragraph", text: "I ran validation locally: 29 queries across five categories — in-domain English, in-domain Hindi, out-of-domain, edge cases, and queries similar to in-domain that shouldn't match. I replicated the exact same notebook on a shared instance afterward. Same code, same document corpus, same embedding model. The confidence scores had shifted across the board." },
      { type: "paragraph", text: "Every category moved up, but not by the same amount. Out-of-domain queries moved the most in relative terms — which is the part that actually matters for a routing decision. Two numbers from this dataset are worth separating clearly, because in an earlier draft I conflated them: the 289% figure is the out-of-domain category specifically. The 129% figure is broader — OOD, edge cases, and similar-but-different averaged together. Both are real, both come from the same dataset; they just answer different questions." },
      { type: "quote", text: "Out-of-domain average: 0.085 → 0.331. A 289% increase. The queries that should score lowest moved the most." },
      { type: "paragraph", text: "The practical consequence: a threshold tuned on the local environment's scores (0.390) doesn't transfer to shared. Recomputing it on shared data moves the optimal cutoff to 0.560. Using the old threshold on the new score distribution would have routed a meaningfully higher share of off-topic queries straight to the knowledge base instead of the LLM fallback — silently, with no error raised." },
      { type: "paragraph", text: "To put it in perspective: in a telephony system, when a customer asks a question, we decide whether we have a good answer in our documentation or should use AI to generate a response. On the shared system, even completely unrelated questions — \"What's the weather?\" or \"Tell me a joke\" — were getting much higher confidence scores. We might incorrectly think we have a good answer when we don't." },
      { type: "heading", text: "The Investigation" },
      { type: "subheading", text: "Ruling Out the Obvious Suspect" },
      { type: "paragraph", text: "The shared environment was running ChromaDB 1.0.20 — built on a Rust-rewritten core (RustBindingsAPI) — versus the pure-Python SegmentAPI implementation locally at 0.5.23. The natural hypothesis: the Rust rewrite changed how raw distance gets converted into a similarity score. Chroma's own announcement says the new core is 4× faster, but faster isn't the same claim as different. I tested each layer directly." },
      { type: "code", text: "# Five layers tested in order:\n\n# 1. Raw L2 distance, synthetic vectors, l2 space\n#    → Identical. Squared L2 in both versions. Not the cause.\n\n# 2. Same test, cosine space\n#    → Identical. 0.006116 / 1.0 / 2.0 in both. Not the cause.\n\n# 3. langchain-chroma version\n#    → 0.1.4 (local) vs 1.1.0 (shared). New suspect → test 4.\n\n# 4. Full similarity_search_with_relevance_scores wrapper\n#    → Identical relevance scores, both versions. Not the cause.\n\n# 5. Embedding model output\n#    → Cosine similarity identical to 6 decimal places. Not the cause." },
      { type: "subheading", text: "Eliminating the Embeddings" },
      { type: "paragraph", text: "I diffed the two embedding space renders pixel by pixel rather than eyeball them. The entire plot region came back byte-for-byte identical — zero difference. The only pixels that differed at all were inside the legend's text box, and that was font-rendering anti-aliasing from two different operating systems, not data. The embeddings are not the cause." },
      { type: "heading", text: "What's Left" },
      { type: "paragraph", text: "Given that HNSW is an approximate nearest-neighbor index, the Python/SegmentAPI path (local, 0.5.23) and the Rust/RustBindingsAPI path (shared, 1.0.20+) may build structurally different graphs with different traversal and different approximation quality from the same embeddings, once you're at real corpus scale. Even though the underlying distance math is provably identical." },
      { type: "paragraph", text: "I still don't have a definitive root cause, and I'm not going to pretend I do. What I have is a fully eliminated stack — raw distance, default space, formula selection, formula implementation, and the embeddings themselves — all provably identical across the two environments, alongside a production score gap that's real anyway. If it is HNSW build-time variance then it's not something I can fix by pinning a version number. It's a property of how approximate indexes work at scale, and I may never get a clean answer without instrumenting the index construction itself." },
      { type: "quote", text: "The bug isn't really the point. The point is what 'same code' turned out to mean in practice: identical Python, identical corpus, identical model — yet still not the same system." },
      { type: "paragraph", text: "If I'd trusted that on faith, the shared environment would have been routing customers to an LLM with confidence scores calibrated for a completely different distribution. Silently. The fix is not a formula or an upgrade. This experiment proves you cannot assume that an upgrade is safe just because the diff looks small. Re-validate your thresholds every time your environment changes, not just when your code does. If a system can fail this silently while doing everything 'right,' the failure mode isn't in the code." },
      { type: "divider" },
      { type: "subheading", text: "TL;DR" },
      { type: "paragraph", text: "Same code, same corpus, same embedding model — shared environment produced scores ~2–4× higher on out-of-domain queries. The obvious hypothesis (Rust rewrite changed the distance formula) was disproven across five layers. Residual cause is most likely HNSW index-construction variance at real corpus scale — untested, honestly flagged as open. Practical takeaway: re-validate thresholds on every environment change, not just every code change." },
    ],
  },
  "intel-sgx": {
    title: "Intel SGX: The CPU-Based Defense System",
    date: "2022-11",
    readTime: 5,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "According to Intel, its Software Guard Extensions (SGX) allows user-level code to allocate private regions of memory called enclaves, which are designed to be protected from processes running at higher privilege levels. What stands out is that SGX is a CPU-based defense system — because it allows applications to run in private memory space, overall system vulnerability is reduced. When an application runs inside an enclave, the CPU instantly encrypts it and stores the key inside itself, where it cannot be obtained by inspecting system memory. Spectre is an Intel processor vulnerability, but even that didn't seem to affect SGX enclaves — the enclave security was designed to prevent even operating systems from accessing the data inside." },
      { type: "heading", text: "Where It Started Breaking" },
      { type: "paragraph", text: "Till now, Intel SGX seemed impenetrable. Then SGXPECTRE arrived. This attack exploits a race condition between injected, speculatively executed memory references, which leads to side-channel observable cache traces and latency of branch resolution — a Spectre-like attack that works specifically against SGX enclaves." },
      { type: "paragraph", text: "ÆPIC Leak is a separate architectural flaw that also enables attacks against SGX enclaves. It forces specific data into caches, leaking targeted secrets. The Advanced Programmable Interrupt Controller (APIC) mechanism manages and routes interrupts, but there exists a bug — an uninitialized memory read — which happens when memory space is not cleared after the CPU is done processing it, causing old data to leak out." },
      { type: "paragraph", text: "The most striking practical demonstration: a group of security researchers examining the Secret Network — a protocol focused on private transactions — for ÆPIC Leak vulnerabilities found the master decryption key for the entire network. The vulnerability was related to Intel SGX." },
      { type: "heading", text: "What Still Holds Up" },
      { type: "paragraph", text: "Despite the attack surface expanding, there are real applications where the properties of SGX remain valuable. Intel, R3, and Hope for Justice collaborated to build an application that enables organisations combating modern slavery to share sensitive case data confidently. The application uses SGX to allow multiple organisations to collaborate on shared analysis and validate algorithms while shielding confidential data from other parties — a use case where the enclave model, even imperfect, provides something difficult to replicate otherwise." },
      { type: "divider" },
      { type: "paragraph", text: "SGX is not what it first appeared to be. But 'not impenetrable' is different from 'not useful.' The lesson is probably about how we reason about security guarantees — and how quickly the attack surface around a system evolves even when the system itself hasn't changed." },
    ],
  },
 
  "xenobots": {
    title: "Xenobots: The First Ever Living Robots",
    date: "2023-02",
    readTime: 4,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "Xenobots are living, programmable organisms. That is a wild statement but it is true. These new creatures were designed on a supercomputer at the University of Vermont and then assembled and tested by biologists at Tufts University — appropriate given that xenobots are neither completely robotic nor a known animal species." },
      { type: "heading", text: "What They Can Do" },
      { type: "paragraph", text: "Apart from being genuinely strange, xenobots were designed to perform specific tasks: moving towards a target, or carrying medicine to a location inside a patient. Despite being less than a millimeter wide, these organisms can move, work together in groups, self-heal, and reproduce. That last one is the interesting part." },
      { type: "paragraph", text: "The reproduction mechanism differs from any other known biological reproduction. Xenobots use kinetic replication — they can create copies of themselves from any level of movement or action. This is not metaphor. The cells literally aggregate into new organisms through motion." },
      { type: "heading", text: "The Obvious Follow-Up Question" },
      { type: "paragraph", text: "Before any conspiracies arise: the researchers confirmed that these organisms were contained in the lab and, being biodegradable, can be easily deactivated. They are also regulated by ethics experts. The researchers were clearly aware that 'self-replicating organism' is a phrase that requires some immediate reassurance." },
      { type: "subheading", text: "Proposed applications" },
      { type: "paragraph", text: "Collecting microplastics in the ocean, inspecting root systems of plants, and regenerative medicine. The common thread is tasks that require navigating spaces and scales that are difficult for conventional robotics — and where biodegradability is a feature rather than a limitation." },
      { type: "divider" },
      { type: "paragraph", text: "The thing that sticks with me is the design process: a supercomputer generating an anatomical blueprint, biologists assembling it from frog skin and heart muscle cells. The boundary between designed artifact and living organism is doing something unusual here." },
    ],
  },
 
  "captcha": {
    title: "CAPTCHA: What Is It and How Does It Work?",
    date: "2023-03",
    readTime: 5,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "CAPTCHA stands for Completely Automated Public Turing test to tell Computers and Humans Apart. The test is designed to determine whether a user is human or a bot. The original version required users to identify the correct sequence of distorted characters — the assumption being that bots couldn't reliably parse them and would, at best, input a random string, making it statistically unlikely they'd pass. Then ML got better at reading distorted text, and the arms race began." },
      { type: "heading", text: "What Google reCAPTCHA Actually Does" },
      { type: "paragraph", text: "Google reCAPTCHA is a free service that moved away from distorted text toward more complex verification. Three main variants:" },
      { type: "subheading", text: "Image recognition" },
      { type: "paragraph", text: "The most common current form — \"select all images containing a traffic light.\" Fairly intuitive, but also solvable by bots with image recognition models. The defense is using blurry or ambiguous images, which degrades ML accuracy but also degrades user experience. The arms race continues." },
      { type: "subheading", text: "The checkbox" },
      { type: "paragraph", text: "The \"I am not a robot\" checkbox is not actually verified by the click itself — it's verified by the path the cursor takes approaching the box. Even the most direct human movement contains micro-variations that bots struggle to replicate authentically. If the cursor analysis is inconclusive, the system inspects stored cookies and browsing history. If that's still inconclusive, it falls back to an image challenge." },
      { type: "subheading", text: "Behavioural assessment" },
      { type: "paragraph", text: "The latest version takes a holistic view: the user's history of interacting with web content, browsing patterns, and contextual signals. A score from 0.0 to 1.0 is assigned — closer to 0.0 means more likely to be a bot. If the score is borderline, an additional challenge is presented." },
      { type: "quote", text: "So yes, reCAPTCHAs do access browsing history. The test is continuous and invisible, not just the moment you click the box." },
      { type: "heading", text: "The Underlying Problem" },
      { type: "paragraph", text: "Every CAPTCHA advance has eventually been defeated by a corresponding ML advance. The behavioural assessment approach is interesting because it makes the test harder to target directly — you'd need to fake an entire browsing history, not just solve a discrete puzzle. But it also means the verification system has significant visibility into user behaviour as a side effect of doing its job." },
    ],
  },
 
  "lava-lamps": {
    title: "How Lava Lamps Help With Internet Encryption",
    date: "2023-04",
    readTime: 6,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "Encryption is the process of encoding information so that only authorised parties can access it — transforming plaintext into ciphertext using an algorithm and a key. The key controls both encryption and decryption. Every new key must be random, and this is where computers have a fundamental problem." },
      { type: "heading", text: "The Randomness Problem" },
      { type: "paragraph", text: "Computers run on logic. Even their random number generators are deterministic — seeded from the current time in milliseconds, then run through a formula. Predictable in principle. This creates a genuine security issue: if your encryption keys are generated by a predictable process, they can be attacked by someone who knows or can guess the seed." },
      { type: "code", text: "// Simplified Math.random() — not actually random\nfunction nextRandom(seed) {\n  seed = (seed * 25214903917 + 11) % Math.pow(2, 48)\n  return seed / Math.pow(2, 48)\n}" },
      { type: "paragraph", text: "Randomness in encryption matters for several compounding reasons: it adds complexity that resists brute-force attacks, prevents patterns from emerging in ciphertext, strengthens key generation, and resists cryptanalysis. A lack of true randomness at the key generation step propagates weakness through everything downstream." },
      { type: "heading", text: "The Lava Lamp Solution" },
      { type: "paragraph", text: "To produce unpredictable data, you need a source of physical randomness — something outside the deterministic logic of the computer itself. The real world is an excellent random data generator. Cloudflare's specific solution: a wall of 100 lava lamps with a camera pointed at them." },
      { type: "paragraph", text: "Lava lamps are constantly, irreproducibly random — the \"lava\" never takes the same shape twice. The camera photographs the wall at regular intervals. Each digital image is stored as a series of numbers (one per pixel), producing a string of values that are genuinely unpredictable. Cloudflare's servers use these as a seed for generating SSL/TLS encryption keys." },
      { type: "quote", text: "The camera takes photos of the lamps at regular intervals and sends the images to Cloudflare servers. Each image becomes a string of totally random numbers that the servers use as a starting point for creating secure encryption keys." },
      { type: "paragraph", text: "Besides being aesthetically on point, the wall provides strong, sufficiently random entropy for encryption at scale. An earlier version of the same idea was introduced by a company called Silicon Graphics — Cloudflare extended it." },
      { type: "divider" },
      { type: "paragraph", text: "What I find interesting here is that the solution to a fundamental limitation of computing is to pipe in the physical world. Not a software fix — a camera. The randomness was always available; it just required looking outward rather than inward." },
    ],
  },
 
  "clock-sync": {
    title: "Automatic Synchronisation of Clocks and Devices",
    date: "2023-04",
    readTime: 6,
    type: "exploratory",
    blocks: [
      { type: "paragraph", text: "During November 2021, my friends and I went out at midnight to watch Daylight Savings Time end in real time. Taking a walk was our best strategy for staying awake for it. At the time I was more focused on the celebration than on the fact that every device in everyone's pockets adjusted its time automatically, simultaneously, without any of us doing anything. It was only while travelling to London later that I actually wondered how that works." },
      { type: "heading", text: "The Infrastructure Behind It" },
      { type: "subheading", text: "Time servers and NTP" },
      { type: "paragraph", text: "Most devices rely on time servers to maintain accurate time. Time servers are synchronised with atomic clocks — the most accurate timekeeping devices in existence. The standard protocol for this synchronisation is NTP (Network Time Protocol), which allows devices to connect to time servers over the internet and retrieve precise time information. Most smartphones, running either Android or iOS, use NTP as their primary time reference." },
      { type: "subheading", text: "Carrier network time" },
      { type: "paragraph", text: "Mobile phones can also receive time information from the cellular network directly. Cellular networks receive time updates from global time servers and satellites, then propagate that to connected devices. This is particularly useful when a device moves between time zones — the network can detect the change and push an update before the device has even queried an NTP server." },
      { type: "subheading", text: "GPS synchronisation" },
      { type: "paragraph", text: "GPS satellites carry highly accurate atomic clocks. GPS receivers determine current time and location from satellite signals, accurate to within a few billionths of a second. Critical systems — air traffic control, financial trading platforms — rely on GPS time rather than NTP because the precision requirements are stricter than internet time servers can reliably provide." },
      { type: "subheading", text: "Stratum hierarchy" },
      { type: "paragraph", text: "NTP servers are organised into stratum levels. A stratum 0 server is directly connected to a reference source like an atomic clock. Stratum 1 servers synchronise with stratum 0 servers, and the hierarchy continues to stratum 15, which represents an unsynchronised device. Devices aim to synchronise with the highest-stratum (most accurate) servers available, and can switch between sources for redundancy." },
      { type: "heading", text: "Why Accuracy Matters Beyond Phones" },
      { type: "paragraph", text: "Accurate time synchronisation is foundational in financial trading, where timestamps on transactions are legally and operationally significant. In telecom networks, frequency synchronisation (not just time, but the rate at which time passes as measured by the network) is required to keep components stable. In data centres, log timestamps from multiple systems need to be consistent enough to reconstruct event sequences accurately during an incident." },
      { type: "paragraph", text: "DST handling is built into most time servers — they're aware of regional daylight saving rules and propagate the adjustment automatically. The device doesn't need to know when DST starts or ends for its region; the server tells it." },
      { type: "divider" },
      { type: "paragraph", text: "Random airport musings aside: the fact that this works seamlessly, globally, across billions of devices simultaneously is one of those pieces of infrastructure that becomes invisible precisely because it works so well. The midnight walk was a good excuse to think about it." },
    ],
  },
}
